version: '3.9'

services:
  portal:
    container_name: portal
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PORT: 8000
    ports:
      - "8000:8000"

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eldoseldos
      POSTGRES_DB: portal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portal"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

