version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/go:1.20.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Install Dependencies
          command: go mod download

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - ~/project


  deploy:
    docker:
      - image: cimg/go:1.20.1-node

    working_directory: ~/project

    steps:
      - attach_workspace:
          at: ~/project


      - run:
          name: Run build
          command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o goportal ./main.go

      - run: sudo apt update
      - run: sudo apt install rsync sshpass -y

      - run: mkdir ~/.ssh && ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run: sshpass -p "edAeqC4md5HsWN" -v rsync -azuP --delete-before . $SSH_USER@$SSH_HOST:~/dev/backend/goportal
      - run: sshpass -p "edAeqC4md5HsWN" -v ssh $SSH_USER@$SSH_HOST sudo systemctl start goportal.service && sudo systemctl enable goportal.service



workflows:
  build-and-sync:
    jobs:
      - build
      - deploy:
          requires:
            - build

