version: 2.1

jobs:
#  lint:
#    docker:
#      - image: golangci/golangci-lint:v1.37-alpine
#    steps:
#      - checkout
#      - run: golangci-lint run

  build:
    working_directory: ~/project/go/src
    docker:
      - image: golang:1.20-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}

      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - ~/project/go/pkg/mod

      - run:
          name: Run build
          command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o portal ./main.go


  deploy-prod:
    docker:
      - image: golang:1.20-alpine

    working_directory: ~/project

    steps:
      - attach_workspace:
          at: ~/project

      - run: sudo apt update
      - run: sudo apt install rsync sshpass -y

      - run: mkdir ~/.ssh && ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

      - run: sshpass -e rsync -azuP --delete-before . $SSH_USER@$SSH_HOST:SSH_DIR_BACK
      - run: sshpass -e ssh $SSH_USER@$SSH_HOST ./portal


workflows:
  build-and-sync:
    jobs:
#      - lint
      - build
      - deploy-prod