PORT: 8080

ENV_MODE: 'develop'
IS_PROD: false
IS_JSON: false

#PG_DSN: postgres://postgres:eldoseldos@postgres:5432/portal?sslmode=disable
PG_DSN: "postgresql://portaladmin:IQUHEMz7x2qjN2sn@localhost:5432/portal?sslmode=disable"

S3_ENDPOINT: "archive.pscloud.io"
S3_ACCESS_KEY: "30ALB0CVRRFWXQLQYMN3"
S3_SECRET_KEY: "bsluZnKE7iJdyADjrltqWlJ0z4sZEZ8PIHyzjJcI"
S3_BUCKET_NAME: "b2b-akcent"
S3_USE_SSL: true