PORT: 8080

ENV_MODE: 'development'
ZAP_JSON: false

PG_DSN: postgres://postgres:eldoseldos@localhost:5432/gotemplate?sslmode=disable
#PG_DSN: "postgresql://portaladmin:IQUHEMz7x2qjN2sn@localhost:5432/portal?sslmode=disable"
RABBIT_MQ_DSN: amqp://guest:guest@localhost:5672

S3_ENDPOINT: "archive.pscloud.io"
S3_ACCESS_KEY: "30ALB0CVRRFWXQLQYMN3"
S3_SECRET_KEY: "bsluZnKE7iJdyADjrltqWlJ0z4sZEZ8PIHyzjJcI"
S3_BUCKET_NAME: "b2b-akcent"
S3_USE_SSL: true